### ISSUE TITLE
Invalid Release 1.0.17

### ISSUE THREAD

**Issue by mreiche** [T-Systems-MMS/aurelia-components#11]
The Release 1.0.17 is already released on NPM: https://www.npmjs.com/package/t-systems-aurelia-components and done before [the last merge](https://github.com/T-Systems-MMS/aurelia-components/pull/10), which should be 1.0.18.

**Comment by Zsar** [comment]
True. I had hoped I could just replace it but no dough. Alas, I'll see to it later today. ... It might be better to only release from master. `npm pack` can be used for local dependencies, if something has to be patched immediately.

**Comment by Zsar** [comment]
Btw. @mreiche I just noticed that we have erroneously removed _all_ your access rights. Restoring. Need you to do a bit of button mashing on the invites because I cannot recall which level it should have been. ~~

**Comment by mreiche** [comment]
Full Owner :)
